import './globals.css'
import { Inter, Roboto, Lexend_Peta, Rowdies } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })
const rowdies = Rowdies({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'creative campaigns',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rowdies.className}>{children}</body>
    </html>
  )
}
